Foxxlegacy.Web/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Foxxlegacy.ViewModel.ViewModel;
using Foxxlegacy.Services.Contacts;
namespace Foxxlegacy.Web.Controllers
{
    public class ContactsController : BaseController
    {
        #region Fields
        private readonly IContactsService _contactsService;

        #endregion

        #region CTor
        public ContactsController
            (
            IContactsService contactsService

            )
        {
            this._contactsService = contactsService;

        }
        #endregion
        // GET: Contacts
        public ActionResult ContactAdmin()
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
                model.ID = 0;

                model.FromUsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(3, model);
                if (TempData.ContainsKey("SUCCESS_MESSAGE"))
                {
                    TempData["SUCCESS_MESSAGE"] = "success";
                }
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult ContactAdmin(ContactUsViewModel model)
        {

            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {
                if (ModelState.IsValid)
                {
                    var loggedInUser = GetCacheUserInfo();
                    long UserId = GetCacheUserInfo().UserId;
                    model.UsersID = 0;// Pending Need to Done
                    model.FromUsersID = UserId;
                    model.IpAddress = "50.209.90.241";//Pending Need to Done
                    model.Origin = "Reps back office";
                    _baseModel = _contactsService.ContactsInsertUpdate(1, model);
                    if (_baseModel.RowAffected > 0)
                    {
                        TempData["SUCCESS_MESSAGE"] = "success";

                        ModelState.Clear();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return RedirectToAction("ContactAdmin");
        }

        [HttpGet]
        public JsonResult GetContactUsById(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
                model.ID = Convert.ToInt64(ID);
                model.FromUsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(3, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddyourComments(ContactUsViewModel model)
        {
            
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                long UserId = GetCacheUserInfo().UserId;

                model.UsersID = UserId;
                _baseModel = _contactsService.ContactsInsertUpdate(4, model);
                model.contactUsListViewModel = _contactsService.GetContactUsList(5, model);
                if (_baseModel.RowAffected > 0)
                {
                    TempData["SUCCESS_MESSAGE"] = "success";

                   
                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetyourComments(ContactUsViewModel model)
        {
            
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {
                
                model.contactUsListViewModel = _contactsService.GetContactUsList(5, model);
                if (_baseModel.RowAffected > 0)
                {
                    TempData["SUCCESS_MESSAGE"] = "success";


                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ClosethisContact(ContactUsViewModel model)
        {
            //ContactUsViewModel model = new ContactUsViewModel();
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                long UserId = GetCacheUserInfo().UserId;

                model.UsersID = UserId;
                _baseModel = _contactsService.ContactsInsertUpdate(6, model);

                if (_baseModel.RowAffected > 0)
                {
                    


                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult MyContacts()
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
              
                model.UsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(7, model);
               
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return View(model);
        }

        [HttpGet]
        public JsonResult GetMyContactsById(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                
                model.ID = Convert.ToInt64(ID);
               
                model.contactUsListViewModel = _contactsService.GetContactUsList(8, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult deleteMyContacts(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                
                model.ID = Convert.ToInt64(ID);

                _baseModel = _contactsService.ContactsInsertUpdate(9, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(_baseModel, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult UpdateMyContacts(ContactUsViewModel model)
        {
           
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                _baseModel = _contactsService.ContactsInsertUpdate(10, model);
                model.contactUsListViewModel = _contactsService.GetContactUsList(8, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

Foxxlegacy.Web/Views/Contacts/ContactAdmin.cshtml
@model Foxxlegacy.ViewModel.ViewModel.ContactUsViewModel
@{
    ViewBag.Title = "ContactAdmin";
    Layout = "~/Views/Shared/_MembersLayout.cshtml";
}

<div class="dashboard_main">
    <div class="row">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_l">
                <h2>Contact Admin</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_r">
                <a href=""> <i class="fa fa-question-circle" aria-hidden="true"></i> Help with this section</a>
            </div>
        </div>
    </div>
    <div class="dashboard_main_inner">


        <div class="col-md-10 col-sm-12 co-xs-12">

            <div class="row">
                <div class="contactadmin_form">
                    <h3>
                        Please fill out the contact request form below.
                    </h3>

                    <span id="lblComplete" style="color:#C00000;font-size:Small;font-weight:bold;@(TempData["SUCCESS_MESSAGE"]=="success"?"display:block":"display:none")">
                        <p>Your contact has been submitted. You should receive a response to this contact within one business day. When our customer service representatives have addressed your concerns, the status of your contact will change in the table below. <br>If you prefer to talk with&nbsp;our friendly Customer Service Representatives, please call 1 888 884-8661 Monday through Friday 8am to 8pm.</p>
                        <p>Thank you for contacting Foxx Legacy Admin Support.</p>
                    </span>
                    @using (@Html.BeginForm("ContactAdmin", "Contacts", FormMethod.Post))
                    {
                        <div class="row">
                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <label>Name:</label>
                            </div>
                            <div class="col-md-4 col-sm-12 col-xs-12">

                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", id = "Name", placeholder = "Jonnathan King", autocomple = "off" })
                                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="clearfix"></div>

                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <label>Email:</label>
                            </div>
                            <div class="col-md-4 col-sm-12 col-xs-12">
                                @Html.TextBoxFor(x => x.EmailId, new { @class = "form-control", id = "EmailId", placeholder = "legal@foxxlegacy.com" })
                                @Html.ValidationMessageFor(x => x.EmailId, "", new { @class = "text-danger" })

                            </div>
                            <div class="clearfix"></div>

                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <label>Phone:</label>
                            </div>
                            <div class="col-md-4 col-sm-12 col-xs-12">
                                @Html.TextBoxFor(x => x.Phone, new { @class = "form-control validnumeric", id = "Phone", placeholder = "17157719075", type = "tel",maxlength=10 })
                                @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })

                            </div>
                            <div class="clearfix"></div>

                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <label>Subject:</label>
                            </div>
                            <div class="col-md-8 col-sm-12 col-xs-12">
                                @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", id = "Subject" })
                                @Html.ValidationMessageFor(x => x.Subject, "", new { @class = "text-danger" })

                            </div>
                            <div class="clearfix"></div>

                            <div class="col-md-2 col-sm-12 col-xs-12">
                                <label>Comments Questions:</label>
                            </div>
                            <div class="col-md-8 col-sm-12 col-xs-12">
                                @Html.TextAreaFor(x => x.Message, new { @class = "form-control", id = "Message", style = "height:150px;" })


                            </div>
                            <div class="clearfix"></div>

                            <div class="col-md-2 col-sm-12 col-xs-12"></div>
                            <div class="col-md-8 col-sm-12 col-xs-12">
                                <input type="submit" class="contactadminbutton" value="Submit your Question or Comment to Administrator Staff" />
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    }
                </div>
            </div>

            <div class="row">

                <p>
                    Select A Contact To View
                </p>
                <div class="table-responsive notificationtable">
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <th></th>
                            <th>Date</th>
                            <th>Subject</th>
                            <th>Your Comments / Questions</th>
                            <th>Answered</th>
                        </tr>
                        @if (Model.contactUsListViewModel.Count > 0)
                        {
                            foreach (var item in Model.contactUsListViewModel)
                            {
                                <tr>
                                    <td style="white-space:nowrap"><a class="changepasswordbtn" data-toggle="modal" data-target="#myModal" href="javascript:void(0)" id="viewId" data-ID="@item.ID">View</a></td>
                                    <td style="white-space:nowrap">@item.EventDate</td>
                                    <td style="white-space:nowrap">@item.Subject</td>
                                    <td style="white-space:nowrap">@item.Details</td>
                                    <td style="white-space:nowrap">
                                        @(@item.OwnerAnswered==false? "Not Answered":"Answered")
                                    </td>
                                </tr>
                            }
                        }



                    </table>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>



    <!--Modal div popup for View Button start-->
    <div class="modal fade donemodal" id="myModal" role="dialog">
        <div class="modal-dialog modal-md" id="credit_card_modal" role="document">
            <div class="modal-content popsecond">

                <div class="modal-body modal-style-bg modalheading">
                    <h5>Contact Admin Details</h5>
                    <div class="clearfix"></div>


                </div>
                <div id="InvalidDataMsg"></div>
                
                <div class="notificationtable">
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                            <tr>
                                <td>
                                    <input type="hidden" id="ContactsId" />
                                    <span class="contact_icon">Admin's response to your contact.</span>
                                    <div class="clearfix"></div>
                                    <strong>Date: </strong>
                                    <span id="lblDate"></span>
                                    <br>
                                    <strong>Subject: </strong>
                                    <span id="lblSubject"></span>
                                    <br>
                                    <strong>Your Question: </strong>
                                    <span id="lblDetails"></span>
                                    <br>
                                    <hr style="width: 100%; color: #4a89dc; height: 2px;">

                                    <strong>Dialogue:</strong><br>

                                    No Dialogue has been started For this contact.
                                    <div style="clear: both;" id="AddyourComments"></div>

                                    <br>
                                    <hr style="width: 100%; color: #4a89dc; height: 2px;">
                                    <table cellpadding="0" cellspacing="0" width="100%">
                                        <tbody>
                                            <tr>
                                                <td colspan="2">You can add your comments to the conversation or archive this contact.</td>
                                            </tr>
                                            <tr>
                                                <td style="padding-right:10px;">
                                                    <textarea name="txtDialogue" rows="5" cols="20" id="DialogueId" style="width:400px;"></textarea>
                                                </td>
                                                <td style="text-align: center;">
                                                    <input type="submit" name="btnAddDialogue" value="Add your comments" class="changepasswordbtn" id="btnAddDialogue" style="width:150px;">
                                                    <br>
                                                    OR<br>
                                                    <input type="submit" name="btnArchive" class="changepasswordbtn" value="Close this contact" id="btnArchive" style="width:150px;">
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <input type="submit" name="btnCxl" class="changepasswordbtn" value="Close Page" id="btnCxl" data-dismiss="modal">
            </div>
        </div>
    </div>


    <!--Modal div popup for View Button End-->
</div>

@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/Js/ContactAdmin")

Foxxlegacy.Web/Views/Contacts/MyContacts.cshtml
@model Foxxlegacy.ViewModel.ViewModel.ContactUsViewModel
@{
    ViewBag.Title = "MyContacts";
    Layout = "~/Views/Shared/_MembersLayout.cshtml";
}

<div class="dashboard_main">
    <div class="row">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_l">
                <h2>My Contacts</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_r">
                <a href=""> <i class="fa fa-question-circle" aria-hidden="true"></i> Help with this section</a>
            </div>
        </div>
    </div>
    <div class="dashboard_main_inner">
        <p>
            Contacts from the Foxx Legacy website will be displayed below. Click the Select button to view the contact details.
        </p>
        <br />
        <p>
            Click Select to view Message
        </p>
        <div class="col-md-12 col-sm-12 co-xs-12">
            <div class="row">
                <div class="table-responsive notificationtable">
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <th></th>
                            <th>Date</th>
                            <th>Origin</th>
                            <th>Name</th>
                            <th>Subject</th>
                        </tr>
                        @if (Model.contactUsListViewModel.Count > 0)
                        {
                            foreach (var item in Model.contactUsListViewModel)
                            {
                                <tr>
                                    <td><a class="changepasswordbtn" data-toggle="modal" data-target="#MyContactsEditModal" href="javascript:void(0)" id="MyContactsSelectId" data-ID="@item.ID">Select</a></td>
                                    <td>@item.EventDate</td>
                                    <td>@item.Origin</td>
                                    <td>@item.Name</td>
                                    <td>@item.Subject</td>

                                </tr>
                            }
                        }

                    </table>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <!-- Modal Start Section -->
    <div class="modal fade" id="MyContactsEditModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
               
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">My Contacts</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-8 col-xs-12 col-xs-12">
                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Origin
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Origin, new { @class = "form-control", @id = "Origin", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Date
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.EventDate, new { @class = "form-control", @id = "EventDate", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Name
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @id = "Name", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Email
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.EmailId, new { @class = "form-control", @id = "EmailId", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Phone
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", @id = "Phone", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Subject
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @id = "Subject", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                                <div class="myinfobox">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Details
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Details, new { @class = "form-control", @id = "Details", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="myinfobox" id="NotesdivTextBoxFor" style="display:none">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Notes
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextBoxFor(x => x.Notes, new { @class = "form-control", @id = "NotesTextbox", @readonly = "readonly" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="myinfobox" id="NotesdivTextAreaFor">
                                    <div class="myinfotop_l myinfowelcometagl">
                                        <span>
                                            Notes
                                        </span>
                                    </div>
                                    <div class="myinfotop_r myinfowelcometagr">

                                        @Html.TextAreaFor(x => x.Notes, new { @class = "form-control", @id = "NotesTextAreaFor" })

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <input type="hidden" id="ContactsId"/>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btnMyContactsUpdate">Edit</button>

                    </div>
                

            </div>
        </div>
    </div>

    <!-- Modal End Section -->
</div>

@Scripts.Render("~/bundles/Js/MyContacts")