Foxxlegacy.Web/Controllers/AdminPermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using System.IO;
using Foxxlegacy.Services.Members;
using Foxxlegacy.ViewModel.ViewModel;
using Foxxlegacy.Services.User;
using Foxxlegacy.Services.Common;
using Foxxlegacy.Services.Contacts;
using System.Globalization;
using Foxxlegacy.Services.Admin;
using System.Data;
using System.Text.RegularExpressions;
using System.Text;
using static Foxxlegacy.ViewModel.ViewModel.CommonViewModel;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using Foxxlegacy.Web.Helpers;
using Foxxlegacy.Web.Models;

namespace Foxxlegacy.Web.Controllers
{
    [FoxxAuthentication]
    [FoxxAuthorization("admin")]
    public class AdminPermissionController : BaseController
    {
        private readonly IAdminService _adminService;
        private readonly IMembersService _membersService;
        private readonly IUserService _userService;
        private readonly ICommonService _commonService;
        private readonly IContactsService _contactsService;
        // GET: AdminPermission
        public AdminPermissionController
          (
          IAdminService adminService, IMembersService membersService, IUserService userService, ICommonService commonService, IContactsService contactsService

          )
        {
            this._adminService = adminService;
            this._membersService = membersService;
            this._userService = userService;
            this._commonService = commonService;
            this._contactsService = contactsService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Permission()
        {
            PermissionViewModel model = new PermissionViewModel();
            var loggedInUser = GetCacheUserInfo();
            if (loggedInUser.UserName == "cking" || loggedInUser.UserName == "rbaker")
            {
                model._member = _membersService.PopulateRoleList(2);
            }
            else
            {
                model._member = _membersService.PopulateRoleList(1);
            }
            return View(model);
        }
        public ActionResult RoleDetails(string UserName)
        {
            RoleInfoViewModel model = new RoleInfoViewModel();
            try
            {
                model._roleDetails = _membersService.RoleDetailsList(3, UserName);
                model.UserName = UserName;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return PartialView("~/Views/Admin/_RoleInfoView.cshtml", model);
        }
        [HttpPost]
        public ActionResult UserRoleUpdae(RoleInfoViewModel model)
        {
            try
            {
                long i = 0;
                int modelLen = model._roleDetails.Count;
                DataTable dt = new DataTable();
                dt.Columns.Add("row_idx", typeof(long));
                dt.Columns.Add("permission", typeof(bool));
                dt.Columns.Add("user_name", typeof(string));
                dt.Columns.Add("permission_id", typeof(Guid));
                dt.Columns.Add("role_name", typeof(string));
                dt.Columns.Add("role_id", typeof(Guid));
                dt.Columns.Add("user_id", typeof(Guid));
                foreach (var roleData in model._roleDetails)
                {
                    DataRow row = dt.NewRow();
                    try
                    {
                        if (roleData.PermissionRoleId == Guid.Empty || roleData.PermissionRoleId == null)
                        {
                            row["row_idx"] = 0;
                        }
                        else
                        {
                            row["row_idx"] = 1;
                        }
                        row["permission"] = roleData.Permission;
                        row["user_name"] = model.UserName;
                        row["permission_id"] = roleData.PermissionRoleId;
                        row["role_name"] = roleData.RoleName;
                        row["role_id"] = roleData.MainRoleId;
                        row["user_id"] = roleData.UserId;
                        dt.Rows.Add(row);
                    }
                    catch (Exception)
                    {
                    }
                }
                SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
                if (dt.Rows.Count > 0)
                {
                    _baseModel = _membersService.InsertUpdateUserRole(5, dt);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Permission");
        }

        public ActionResult AdminReport()
        {
            AdminReportViewModel model = new AdminReportViewModel();
            //_commonService.GetUsersIDbyUserName(9, adminHomeModel.UserName.Trim());
            model.csjEntries = _membersService.GetCSJEntriesList(1);
            model.correspondence = _membersService.GetCorrespondenceList(2);
            model.PinCertificateList = _adminService.GetPinCertificateList(1);
            model.CallList = _adminService.GetCallList(1);
            model.newUsers = _membersService.GetNewUsersList(3);

            model.ItemByState = _adminService.GetItemByStateList(1);

            model.TotalsbyState = _adminService.GetItemByStateList2(2);


            //Items By Date Start Scetion
            model.MinimumDate = DateTime.Now.Date.AddDays(-7);
            model.MaximumDate = DateTime.Today;
            if (TempData.ContainsKey("GetItemsByDate"))
            {

                TempData["ActiveTab"] = "ItemsByDateTab";
                model = (AdminReportViewModel)TempData["GetItemsByDate"];
                model.ItemByDate = _adminService.GetItemByDateList(3, model);
            }
            //Items By Date End Scetion

            //Items By Product Start Scetion
            model.MinimumDateForProduct = DateTime.Now.Date.AddDays(-7);
            model.MaximumDateForProduct = DateTime.Today;
            if (TempData.ContainsKey("GetItemsByProduct"))
            {

                TempData["ActiveTab"] = "ItemsByProductTab";
                model = (AdminReportViewModel)TempData["GetItemsByProduct"];
                model.MinimumDate = model.MinimumDateForProduct;
                model.MaximumDate = model.MaximumDateForProduct;
                var result = _adminService.GetItemByDateList(4, model);
                model.ItemByProduct = Data.StringToObject<List<ItemByProduct>>(Data.ObjectToString(result));

            }

            //Items By Product End Scetion


            // Maps Order Start Scetion
            model.MinimumDateForOrder = DateTime.Now.Date.AddDays(-7);
            model.MaximumDateForOrder = DateTime.Today;
            if (TempData.ContainsKey("GetMapsOrder"))
            {
                model = (AdminReportViewModel)TempData["GetMapsOrder"];
                model.MinimumDate = model.MinimumDateForOrder;
                model.MaximumDate = model.MaximumDateForOrder;
                model.MapsViewModel = _adminService.GetMapsList(1, model);
                model.MapsOrders = Data.StringToObject<List<MapsOrders>>(Data.ObjectToString(model.MapsViewModel));
                TempData["ActiveTab"] = "MapsOrderTab";
            }

            // Maps Order End Scetion


            // Maps Join Start  Scetion
            model.MinimumDateForJoin = DateTime.Now.Date.AddDays(-7);
            model.MaximumDateForJoin = DateTime.Today;
            if (TempData.ContainsKey("GetMapsJoin"))
            {
                model = (AdminReportViewModel)TempData["GetMapsJoin"];
                model.MinimumDate = model.MinimumDateForJoin;
                model.MaximumDate = model.MaximumDateForJoin;
                model.MapsViewModel = _adminService.GetMapsList(2, model);
                model.MapsJoins = Data.StringToObject<List<MapsJoins>>(Data.ObjectToString(model.MapsViewModel));
                TempData["ActiveTab"] = "GetMapsJoin";
            }

            //Maps Join End Scetion

            // Maps Max Level UserCounts Start  Scetion
            model.MaxLevelUserCounts = _adminService.GetUsercountsbymaxlevelList(1, model);
            model.Usercountsbymaxlevel = Data.StringToObject<List<Usercountsbymaxlevel>>(Data.ObjectToString(model.MaxLevelUserCounts));

            if (TempData.ContainsKey("GetMaxLevelUserCountsDeatis"))
            {
                TempData["ActiveTab"] = "MaxLevelUserCountsTab";
                model.Level = Convert.ToInt64(TempData["GetMaxLevelUserCountsDeatis"]);
                model.MaxLevelUserCounts = _adminService.GetUsercountsbymaxlevelList(2, model);
                model.UsercountsbymaxlevelDetails = Data.StringToObject<List<UsercountsbymaxlevelDetails>>(Data.ObjectToString(model.MaxLevelUserCounts));


                //var jsonString = JsonConvert.SerializeObject(model.MaxLevelUserCounts);
                //model.UsercountsbymaxlevelDetails = Newtonsoft.Json.JsonConvert.DeserializeObject<List<UsercountsbymaxlevelDetails>>(jsonString);


            }
            // Maps Max Level UserCounts Start  Scetion

            // Maps SweepReport Start  Scetion
            model.SweepReport = _adminService.GetSweepReportList(1);

            if (TempData.ContainsKey("PaidDeleteSweepReport"))
            {
                TempData["ActiveTab"] = "SweepReportTab";
            }

            // Maps SweepReport End  Scetion



            //AutoShipCounts Start  Scetion
            model.AutoShipCounts = _adminService.GetAutoShipCountsList(1);
            // AutoShipCounts End  Scetion


            //OutOfStockItem Start  Scetion
            model.OutOfStockItem = _adminService.GetOutOfStockItemList(1);
            foreach (var item in model.OutOfStockItem)
            {

Foxxlegacy.Web/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Foxxlegacy.ViewModel.ViewModel;
using Foxxlegacy.Services.Contacts;
namespace Foxxlegacy.Web.Controllers
{
    public class ContactsController : BaseController
    {
        #region Fields
        private readonly IContactsService _contactsService;

        #endregion

        #region CTor
        public ContactsController
            (
            IContactsService contactsService

            )
        {
            this._contactsService = contactsService;

        }
        #endregion
        // GET: Contacts
        public ActionResult ContactAdmin()
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
                model.ID = 0;

                model.FromUsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(3, model);
                if (TempData.ContainsKey("SUCCESS_MESSAGE"))
                {
                    TempData["SUCCESS_MESSAGE"] = "success";
                }
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult ContactAdmin(ContactUsViewModel model)
        {

            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {
                if (ModelState.IsValid)
                {
                    var loggedInUser = GetCacheUserInfo();
                    long UserId = GetCacheUserInfo().UserId;
                    model.UsersID = 0;// Pending Need to Done
                    model.FromUsersID = UserId;
                    model.IpAddress = "50.209.90.241";//Pending Need to Done
                    model.Origin = "Reps back office";
                    _baseModel = _contactsService.ContactsInsertUpdate(1, model);
                    if (_baseModel.RowAffected > 0)
                    {
                        TempData["SUCCESS_MESSAGE"] = "success";

                        ModelState.Clear();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return RedirectToAction("ContactAdmin");
        }

        [HttpGet]
        public JsonResult GetContactUsById(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
                model.ID = Convert.ToInt64(ID);
                model.FromUsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(3, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddyourComments(ContactUsViewModel model)
        {
            
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                long UserId = GetCacheUserInfo().UserId;

                model.UsersID = UserId;
                _baseModel = _contactsService.ContactsInsertUpdate(4, model);
                model.contactUsListViewModel = _contactsService.GetContactUsList(5, model);
                if (_baseModel.RowAffected > 0)
                {
                    TempData["SUCCESS_MESSAGE"] = "success";

                   
                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetyourComments(ContactUsViewModel model)
        {
            
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {
                
                model.contactUsListViewModel = _contactsService.GetContactUsList(5, model);
                if (_baseModel.RowAffected > 0)
                {
                    TempData["SUCCESS_MESSAGE"] = "success";


                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ClosethisContact(ContactUsViewModel model)
        {
            //ContactUsViewModel model = new ContactUsViewModel();
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                long UserId = GetCacheUserInfo().UserId;

                model.UsersID = UserId;
                _baseModel = _contactsService.ContactsInsertUpdate(6, model);

                if (_baseModel.RowAffected > 0)
                {
                    


                }

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult MyContacts()
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                long UserId = GetCacheUserInfo().UserId;
              
                model.UsersID = UserId;
                model.contactUsListViewModel = _contactsService.GetContactUsList(7, model);
               
            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return View(model);
        }

        [HttpGet]
        public JsonResult GetMyContactsById(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();

            try
            {

                
                model.ID = Convert.ToInt64(ID);
               
                model.contactUsListViewModel = _contactsService.GetContactUsList(8, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult deleteMyContacts(long? ID)
        {
            ContactUsViewModel model = new ContactUsViewModel();
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                
                model.ID = Convert.ToInt64(ID);

                _baseModel = _contactsService.ContactsInsertUpdate(9, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(_baseModel, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult UpdateMyContacts(ContactUsViewModel model)
        {
           
            SqlResponseBaseModel _baseModel = new SqlResponseBaseModel();
            try
            {

                _baseModel = _contactsService.ContactsInsertUpdate(10, model);
                model.contactUsListViewModel = _contactsService.GetContactUsList(8, model);

            }
            catch (Exception ex)
            {
                TempData["ERROR_MESSAGE"] = "Opps something went wrong!";
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

Foxxlegacy.Web/Views/Admin/Commissions1.cshtml
@{
    ViewBag.Title = "Commissions1";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Commissions1</h2>

Foxxlegacy.Web/Views/Admin/Contact.cshtml
@model Foxxlegacy.ViewModel.ViewModel.ArchiveCommonResponseViewModel
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="faq2_admin">
    <div class="tabcontainer_content">
        <h4>
            Contacts:
            <input type="button" value="Common Responses" id="btnCommonResponsediv" />
        </h4>

        <div class="table-responsive">
            <table cellpadding="0" cellspacing="0" width="100%" class="hometable">
                <tr>
                    <th></th>
                    <th>Date</th>
                    <th>UserName</th>
                    <th>Name</th>
                    <th>Subject</th>
                    <th>Dialogue Count</th>
                </tr>
                @if (Model!= null)
                {
                    foreach (var item in Model.archiveCommonResponseListViewModel)
                    {
                        <tr>
                            <td><a href="@Url.Action("Contact_inner","Admin",new {ContactsID=item.ID,UserId=item.FromUsersID })">Select</a></td>
                            <td>@item.EventDate</td>
                            <td>@item.UserName</td>
                            <td>@item.Name</td>
                            <td>@item.subject</td>
                            <td>@item.DialogueCount</td>
                        </tr>
                    }
                }
            </table>
        </div>

    </div>
</div>





<script>
    $(document).on("click", "#btnCommonResponsediv", function () {

        window.location.href = "/Admin/CreateNewCommonResponse";
       

    });
</script>

Foxxlegacy.Web/Views/Admin/Help.cshtml
@model Foxxlegacy.ViewModel.ViewModel.HelpViewModel

@{
    ViewBag.Title = "Help";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="dashboard_main">
    <div class="row">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_l">
                <h2>Back Office Help Center</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_r">

            </div>

        </div>
    </div>
    <div class="dashboard_main_inner">
        @Html.Raw(Model.HelpContent)
        <a href="~/@Model.Return">   <input class="outbtn" type="button" value="Return"></a>

        <div class="clearfix"></div>
    </div>
</div>

<div class="dashboard_main">
    <div class="row">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_l">
                <h2>From Your Friends At Foxx</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_r">

            </div>

        </div>
    </div>
    <div class="dashboard_main_inner">
        @Html.Raw(Model.HelpContent2);

        <div class="clearfix"></div>
    </div>
</div>

Foxxlegacy.Web/Views/Admin/OrdersDetails.cshtml
@model Foxxlegacy.ViewModel.ViewModel.OrderDetailsModel

@{
    ViewBag.Title = "OrdersDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="dashboard_main">
    <div class="row">
        <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_l">
                <h2>Order Details</h2>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="aftermemberlogin_r">
                <a href=""></a>
            </div>
        </div>
    </div>

    <div class="orderdetails">
        <h5>Order ID : #@Model.myOrders.OrderId</h5>
        <p>Order Date <b>@Model.myOrders.OrderId</b></p>
        <p>Order Status <b>@Model.OrderStatus</b></p>
        <p>Order Total <b>$@Model.myOrders.OrderTotal</b></p>
    </div>

    <div class="billingaddress">
        <h5>Billing Address</h5>
        <span>@Model.myOrders.FirstName  @Model.myOrders.LastName</span>
        <span>Email : @Model.myOrders.Email</span>
        <span>Phone No : @Model.myOrders.PhoneNumber</span>
        <span>Fax : @Model.myOrders.FaxNumber</span>
        @*<span>www.apb.com</span>*@
        <span>@Model.myOrders.Address1</span>
        <span>@Model.myOrders.Address2</span>
        <span>@Model.myOrders.ZipPostalCode</span>
        <h5>Payment</h5>
        <span>Payment Method: @Model.myOrders.PaymentMethodSystemName</span>
        <span>Payment Status: @Model.PaymentMethodStatus</span>
    </div>

    <div class="producttable">
        <h5>Products (s)</h5>
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <th>SKU</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
            @{
                foreach (var item in Model.Items)
                {
                    <tr>
                        <td>@item.Sku</td>
                        <td>@item.ProductName</td>
                        <td>$@item.UnitPrice</td>
                        <td>@item.Quantity</td>
                        <td>$@item.Total</td>
                    </tr>
                }
            }
        </table>
    </div>
    <div class="totalprice">
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <th>Sub Total : </th>
                <td>$@Model.myOrders.SubTotal</td>
            </tr>
            <tr>
                <th>Tax : </th>
                <td>$0.0</td>
            </tr>
            <tr>
                <th>Order Total : </th>
                <td><b>$@Model.myOrders.OrderTotal</b></td>
            </tr>
        </table>
    </div>
    <div class="clearfix"></div>
    <div align="right">
        <div>
            <input type="button" value="Back" onclick="location.href='/Admin/OrdersAsPerCustomer?CustomerId=@Model.myOrders.CustomerId'">
        </div>
        @*<input type="button" class="changepasswordbtn1" value="Re-Order" />*@
    </div>
</div>

Foxxlegacy.Web/Views/Admin/_OrganicPlacementTree.cshtml
@model List<Foxxlegacy.ViewModel.ViewModel.ReferralUser>
<ul class="child-tree-node" style="display:block">
    @{
        if (Model.Count > 0)
        {
            foreach (var node in Model)
            {
                <li>
                    @if (node.ChildNodeCount > 0)
                    {
                        <button class="treebutton" type="button" data-id="@node.Id"> + </button>
                    }
                <span id="personalinfo" data-id="@node.Id">
                    @node.Text 
                    @{
                        if (node.IsQualified)
                        {
                            <span class="Qual"><b> Qual</b></span>
                        }
                        else
                        {
                            <span class="NoQual"><b> Qual</b></span>
                        }

                        if (node.IsSms)
                        {
                            <b><i class="fa fa-mobile" style="color:green;" aria-hidden="true"></i></b>
                        }
                        else
                        {
                            <b><i class="fa fa-mobile" style="color:red;" aria-hidden="true"></i></b>
                        }
                        if (node.IsEmail)
                        {
                            <b><i class="fa fa-envelope" style="color:green;" aria-hidden="true"></i></b>
                        }
                        else
                        {
                            <b><i class="fa fa-envelope" style="color:red;" aria-hidden="true"></i></b>
                        }
                        if (true)
                        {
                            if (node.IsPersonalMovable)
                            {
                                <b><i class="fa fa-clock" style="color:black;" aria-hidden="true"></i></b>
                            }
                            @*else if (node.IsPersonalPermanent)
                            {
                                <img title="Personal Permanent" alt="Personal Permanent" src="@Url.Content("~/Images/black-watch.png")" />
                            }
                            else if (node.IsNonPersonalMovable)
                            {
                                <img title="Non-Personal Movable" alt="Non-Personal Movable" src="@Url.Content("~/Images/black-stopwatch.png")" />
                            }
                            else if (node.IsPersonalPermanent)
                            {
                                <img title="Non-Personal Permanent" alt="Non-Personal Permanent" src="@Url.Content("~/Images/black-watch.png")" />
                            }*@
                            <span>Rank:</span> @node.RankText
                        }
                        @*<img class="black-watch-img" title="Non-Personal Permanent" alt="Non-Personal Permanent" src="@Url.Content("~/Images/black-watch.png")" />*@

                <a href="/Members/RankManagementReport?id=@node.Id" target="_blank"> <i class="fa fa-file" aria-hidden="true"></i> Rank management Report</a>
                    }
                </span>
                </li>
            }
        }
    }
</ul>

Foxxlegacy.Web/Views/Admin/_RoleInfoView.cshtml
@model  Foxxlegacy.ViewModel.ViewModel.RoleInfoViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    @using (Html.BeginForm("UserRoleUpdae", "AdminPermission", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.UserName);
        <div class="table-responsive notificationtable">
            <table cellpadding="0" cellspacing="0" width="40%" id="tblRoleInfo">
                <tbody>
                    <tr>
                        <th>Permission</th>
                        <th>
                            Role Name
                        </th>
                    </tr>
                    @{
                        for (int i = 0; i < Model._roleDetails.Count; i++)
                        {
                            <tr>
                                <td style="display:none">@Html.HiddenFor(x => x._roleDetails[i].PermissionRoleId)</td>
                                <td>@Html.CheckBoxFor(x => x._roleDetails[i].Permission)</td>
                                <td>@Html.DisplayFor(x => x._roleDetails[i].RoleName)</td>
                                <td style="display:none">@Html.HiddenFor(x => x._roleDetails[i].MainRoleId)</td>
                                <td style="display:none">@Html.HiddenFor(x => x._roleDetails[i].RoleName)</td>
                                <td style="display:none">@Html.HiddenFor(x => x._roleDetails[i].UserId)</td>
                            </tr>
                        }
                    }
            </table>
        </div>
        <input type="submit" class="transfer_panel_bottom_btn" name="btnUpdate" value="Update" />
    }
</div>
@Scripts.Render("~/bundles/jqueryval")

Foxxlegacy.Web/Views/Admin/_commissionAdminUserWiseView.cshtml
@model List<Foxxlegacy.ViewModel.ViewModel.UserWiseCommissionModel>


@if (Model != null)
{

    foreach (var item in Model)
    {
<tr>
    <td>@item.ID</td>
    <td>@item.Name (@item.UserName)</td>
    <td>@item.RoleName</td>
    <td>@item.OrderCount</td>
    @*<td>@item.OrderTotalCommissionAmount </td>*@

    <td>@item.Amount </td>

</tr>
    }


}

<script>
    $(document).ready(function () {       
        $('#AdminuserWiseCommsionTable').DataTable({
            "pageLength": 25,
            "ordering": false,
            "bDestroy": true
        });
    });

</script>

Foxxlegacy.Web/Views/Admin/_commissionView.cshtml
@model List<Foxxlegacy.ViewModel.ViewModel.ViewCommissionModel>

@if (Model != null)
{
<table cellpadding="0" cellspacing="0" width="100%" class="hometableComm" id="adminCommissionsTable">
    <thead>
        <tr>
            <th>User ID</th>
            <th>User Name (Rank)</th>          
            <th>Order No.</th>
            <th>Commission Type</th>
            <th>Date</th>
            <th>Order Amount</th>
            <th>Order Commission Amount</th>
            <th>Commission %age</th>
            <th>Commission Amount</th>
            <th>Level</th>
            <th>Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.UserId</td>
                <td>@item.UserName (@item.UserRankId)</td>                
                <td>@item.OrderId	</td>
                <td>@item.CommissionType</td>
                <td>@item.CreatedDate	</td>
                <td>@item.OrderAmount</td>
                <td>@item.OrderTotalCommissionAmount </td>
                <td>@item.CommissionPercentage </td>
                <td>@item.CommissionAmount </td>
                <td>@item.CommissionLevel</td>
                <td>@item.RecordType</td>
            </tr>
        }
    </tbody>
    

</table>

}

<script>
    $(document).ready(function () {
        $('#adminCommissionsTable').DataTable({
            "pageLength": 25,
            "ordering": false
        });
    });
    
</script>